version: "3"

vars:
  GLOBAL: "GLOBAL"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l --sort none

  build:
    desc: Build go program
    cmds:
      - go build -o task-executor ./cmd

  run:
    desc: Run go program
    cmds:
      - go run ./cmd -taskfile={{.TF}}
    vars:
      TF: '{{.TF}}'

  run:vars:
    desc: Run vars test program
    cmds:
      - task: run
        vars:
          TF: test/Taskfile.vars.yml

  run:another:
    desc: Run another test program
    cmds:
      - task: run
        vars:
          TF: test/Taskfile.another.yml

  run:includes:
    desc: Run vars test program
    cmds:
      - task: run
        vars:
          TF: test/Taskfile.includes.yml

  run:all:
    desc: Run all test program
    cmds:
      - task: run
        vars:
          TF: test/Taskfile.all.yml

  run:poc:bubbletea:
    desc: Run bubbletea poc program
    cmds:
      - go run ./poc/bubbletea -target={{.TARGET}}
    vars:
      TARGET: '{{.TARGET | default "varInputter"}}'

  run:poc:lipgloss:
    desc: Run lipgloss poc program
    cmds:
      - go run ./poc/lipgloss -target={{.TARGET}}
    vars:
      TARGET: '{{.TARGET | default "tutorial"}}'

  fmt:
    desc: Format go program
    cmds:
      - go fmt ./...

  vet:
    desc: Doctor go program
    cmds:
      - go vet ./...

  gen:
    desc: Generate go code
    cmds:
      - go generate ./...

  test:
    desc: Test all case
    cmds:
      - go test -v ./...

  test:run:
    desc: Test specific case
    cmds:
      - go test -v -run "{{.NAME}}" ./...
    requires:
      vars: [ NAME ]
